name: Build multi-arch docker images

on:
  pull_request:
    branches: release

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Enable experimental Docker features
        run: |
          echo $'{\n    "experimental": true\n}' | sudo tee /etc/docker/daemon.json && sudo service docker restart
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Login to Docker
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build AMD64 image
        run: |
          docker build \
            --output "type=image,push=false" \
            --tag mrosenbjerg/nxplx-webapi:amd64 \
            --squash \
            ./docker/gh-build/amd64
      -
        name: Build ARM64v8 image
        run: |
          docker build \
            --output "type=image,push=false" \
            --tag mrosenbjerg/nxplx-webapi:arm64v8 \
            --squash \
            ./docker/gh-build/arm64v8
      -
        name: Build ARM32v7 image
        run: |
          docker build \
            --output "type=image,push=false" \
            --tag mrosenbjerg/nxplx-webapi:arm32v7 \
            --squash \
            ./docker/gh-build/arm32v7
      -
        name: Push new images
        run: |
          docker push mrosenbjerg/nxplx-webapi:amd64 && \
          docker push mrosenbjerg/nxplx-webapi:arm64v8 && \
          docker push mrosenbjerg/nxplx-webapi:arm32v7
      -
        name: Create and push Docker manifest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker manifest create mrosenbjerg/nxplx-webapi:latest \
            mrosenbjerg/nxplx-webapi:amd64 \
            mrosenbjerg/nxplx-webapi:arm64v8 \
            mrosenbjerg/nxplx-webapi:arm32v7 && \
          docker manifest annotate mrosenbjerg/nxplx-webapi:latest mrosenbjerg/nxplx-webapi:amd64 --arch amd64 --os linux && \
          docker manifest annotate mrosenbjerg/nxplx-webapi:latest mrosenbjerg/nxplx-webapi:arm64v8 --arch arm64 --os linux && \
          docker manifest annotate mrosenbjerg/nxplx-webapi:latest mrosenbjerg/nxplx-webapi:arm32v7 --arch arm --os linux && \
          docker manifest push mrosenbjerg/nxplx-webapi:latest
